# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#0b0c10'
foreground='#c2c2c3'
cursor='#c2c2c3'

# Colors
color0='#0b0c10'
color1='#7FC3CD'
color2='#92A8B2'
color3='#87B6C9'
color4='#A0AFC4'
color5='#88C0D1'
color6='#BDC2CE'
color7='#c2c2c3'
color8='#48484b'
color9='#7FC3CD'
color10='#92A8B2'
color11='#87B6C9'
color12='#A0AFC4'
color13='#88C0D1'
color14='#BDC2CE'
color15='#c2c2c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
