# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#1e1e2e'
foreground='#7f849c'
cursor='#6c7086'

# Colors
color0='#f5e0dc'
color1='#f2cdcd'
color2='#f5c2e7'
color3='#cba6f7'
color4='#f38ba8'
color5='#eba0ac'
color6='#fab387'
color7='#f9e2af'
color8='#a6e3a1'
color9='#94e2d5'
color10='#89dceb'
color11='#74c7ec'
color12='#89b4fa'
color13='#b4befe'
color14='#cdd6f4'
color15='#bac2de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
