# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#24273a'
foreground='#8087a2'
cursor='#6e738d'

# Colors
color0='#f4dbd6'
color1='#f0c6c6'
color2='#f5bde6'
color3='#c6a0f6'
color4='#ed8796'
color5='#ee99a0'
color6='#f5a97f'
color7='#eed49f'
color8='#a6da95'
color9='#8bd5ca'
color10='#91d7e3'
color11='#7dc4e4'
color12='#8aadf4'
color13='#b7bdf8'
color14='#cad3f5'
color15='#b8c0e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
