"Boot with standard options"  "root=/dev/mapper/fedora-root ro rd.lvm.lv=fedora/root rd.luks.uuid=luks-0bb3589e-1fca-4daf-8f4d-3619a79a9d85 rd.lvm.lv=fedora/swap rhgb quiet LANG=fr_CA.UTF-8"
"Boot to single-user mode"    "root=/dev/mapper/fedora-root ro rd.lvm.lv=fedora/root rd.luks.uuid=luks-0bb3589e-1fca-4daf-8f4d-3619a79a9d85 rd.lvm.lv=fedora/swap rhgb quiet LANG=fr_CA.UTF-8 single"
"Boot with minimal options"   "ro root=/dev/mapper/fedora-root"
