# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# - AESTHETICS - #
#

# set statusbar colors
set -g default-terminal "screen-256color"

# statusbar has white on black/transparent background
set -g status-bg default
set -g status-fg white

# active window is blue
set-window-option -g window-status-current-fg blue

# hide left side of status bar
set -g status-left ''

# hide right side of status bar
set -g status-right ''

# hide the surrounding info of window
# setw -g window-status-format ' #(echo "#{pane_current_command}") '
setw -g window-status-format ' #W '
setw -g window-status-current-format ' #W '

# - Functionality - #
#

# automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# use vi mode
setw -g mode-keys vi

# use xterm keys
set -g default-terminal "xterm"

# set esc time becomes 0
set -sg escape-time 0
set -g status-interval 0

# monitor activity on
setw -g monitor-activity on

# shift left to go to previous tab
bind-key -n S-Left previous-window

# shift right to go to next tab
bind-key -n S-Right next-window

# shift up and down keys to toggle status bar
bind-key -n S-Up set-option -g status
bind-key -n S-Down set-option -g status

# mouse mode
set-option -g mouse on
